apiVersion: v1
kind: Deployment
metadata:
  name: ngircd
  namespace: ngircd
  labels:
    app: ngircd
spec:
  replicas: 1
  template:
    metadata:
      name: ngircd
      labels:
        app: ngircd
  spec:
    containers:
      - name: ngircd
        image: docker.io/jremesfoss/ngircd:v0.1
        imagePullPolicy: Always
    restartPolicy: Always
  selector:
    matchLabels:
      app: ngircd
